import type { Metadata } from "next";
import "./globals.css";
import { ConvextClientProvider } from "./convex-client-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConvextClientProvider>
          {children}
        </ConvextClientProvider>
      </body>
    </html>
  );
}
